[package]
name = "service"
version = "1.0.0"
authors = ["The Teaclave Authors"]
build = "build.rs"

[dependencies]
sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_crypto_helper = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
derive_more = "0.99.16"
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0"
serde_derive = "1.0"
sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git", features = ["backtrace"] }

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
sgx_crypto_helper = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
sgx_ucrypto = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }
sgx_urts = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk" }